In [1]:
import h5py 
f = h5py.File('/tmp/my_file.multires', 'w')

In [2]:
f.create_group('resolutions')

<HDF5 group "/resolutions" (0 members)>

In [3]:
# start with a resolution of 1 element per pixel
highest_resolution = 1
array_length = 100000
f['resolutions'].create_dataset('1', (100000,))

<HDF5 dataset "1": shape (100000,), type "<f4">

In [7]:
import numpy as np

f['resolutions']['1'][:] = np.array(range(array_length))


In [33]:
import math
tile_size = 1024
max_zoom = math.ceil(math.log(array_length / tile_size) / math.log(2))

print("max_zoom:", max_zoom)

max_zoom: 7


In [32]:
1024 * 2 ** 7

131072

In [25]:
f['resolutions'].create_dataset('2', (len(f['resolutions']['1']) // 2,))
f['resolutions']['2'][:] = f['resolutions']['1'][:].reshape(-1,2).sum(axis=1)

In [28]:
print(f['resolutions']['1'][:5])
print(f['resolutions']['2'][:5])

[ 0.  1.  2.  3.  4.]
[  1.   5.   9.  13.  17.]


In [8]:
a = np.array(range(10))

In [12]:
next_level = a.reshape(-1,2).sum(axis=1)

array([ 1,  5,  9, 13, 17])